<script>
import MyInput from '../Input.vue'
import BigNumber from '../general/BigNumber.vue'
import {toBN} from 'utils/BN'

export default {
	data(){
		return {
			amount: null,
			popUp: false,
			popUpStep: 0,
			_time: 0,
			intID: null,
			state: 'wait',
			selector:[
				{
					"id":"stake",
					"title":"Stake",
					"path":"/stake/stake"
				},
				{
					"id":"unstake",
					"title":"Unstake",
					"path":"/stake/unstake"
				}
			]
		}
	},
	computed:{
		share(){
			const sh = this.$store.state.tokens.balance.sWHITE
			const total = this.$store.state.staking.totalStaked
			if(!total || total.isZero()) return toBN(0)
			if(sh && total) return sh.mul(10000).div(total)
		},
		estimated(){
				if(!this.amount) return this.share
				const sh = this.$store.state.tokens.balance.sWHITE
				const total = this.$store.state.staking.totalStaked
				if(sh && total) return sh.add(this.amount).mul(10000).div(total.add(this.amount))
		},
		balances(){
			return {
				WHITE: this.$store.state.tokens.balance.WHITE,
				sWHITE: this.$store.state.tokens.balance.sWHITE,
			}
		}
	},
	methods:{
		async stake(){
			await this.$store.dispatch('staking/deposit', this.amount)
		}
	},
	components:{
		MyInput, BigNumber
	}
}
</script>

<template lang="pug">
.swap-text
	| Stake WHITE, get sWHITE #[br.br--mobile] and start earning #[br]
	|
	| a share of USDC fees #[br.br--mobile] generated by Whiteheart
.new-swap.margin-top-32
	.new-swap__box--top
		.table-box-elem__info.center
			| You can stake:
		.token--big-title
			.token.WHITE: big-number(:value='balances.WHITE' ) WHITE
		my-input(
			max
			title="Amount"
			v-model="amount"
			:token="$store.state.tokens.WHITE"
		)
		.separator-arrow
		my-input(
			title="To"
			v-model="amount"
			:token="$store.state.tokens.sWHITE"
		)
		.share-dynamics
			.share-dynamics__elem
				.share-dynamics-elem__title
					| Your current share
					br
					| in staking rewards:
				.share-dynamics-elem__value
					big-number(:value='share' :decimals='2') %
			.separator-arrow.horizontally
			.share-dynamics__elem
				.share-dynamics-elem__title
					| Your estimated share
					br
					| after this staking:
				.share-dynamics-elem__value
					| ~#[big-number(:value='estimated' :decimals='2')]%
		.disclaimer
			.disclaimer__title Disclaimer:
			.disclaimer__text
				| We can’t predict your USDC
				br
				| earnings at this moment:
				br
				| the pool size is still unstable.

		.new-swap__button
			button.button.primary(
					@click="stake"
					:disabled="!amount || amount.isZero() || amount.gt(balances.WHITE)"
				)
				| Stake
</template>
