<script>
import MyInput from '../Input.vue'

export default {
	data(){
		return {
			popUp: false,
			popUpStep: 0,
			_time: 0,
			intID: null,
			state: 'wait',
			selector:[
				{
					"id":"stake",
					"title":"Stake",
					"path":"/stake/stake"
				},
				{
					"id":"unstake",
					"title":"Unstake",
					"path":"/stake/unstake"
				}
			]
		}
	},
	components:{
		MyInput
	}
}
</script>

<template lang="pug">
.swap-text
	| Stake WHITE, get sWHITE 
	br.br--mobile
	|and start earning
	br
	| a share of USDC fees 
	br.br--mobile
	| generated by Whiteheart

.new-swap.margin-top-32
	.new-swap__box--top
		.table-box-elem__info.center
			| You can stake:
		.token--big-title
			.token.WHITE
				| 100 WHITE
		my-input(
			title="Amount"
			token="WHITE"
			:max="true"
			:selector="false"
			:balance="100")
		.separator-arrow
		my-input(
			title="To"
			token="sWHITE"
			:max="false"
			:selector="false"
			:balance="0")
		.share-dynamics
			.share-dynamics__elem
				.share-dynamics-elem__title
					| Your current share
					br
					| in staking rewards:
				.share-dynamics-elem__value
					| 0%
			.separator-arrow.horizontally
			.share-dynamics__elem
				.share-dynamics-elem__title
					| Your estimated share
					br
					| after this staking:
				.share-dynamics-elem__value
					| ~1,7%
		.disclaimer
			.disclaimer__title Disclaimer:
			.disclaimer__text
				| We can’t predict your USDC
				br
				| earnings at this moment: 
				br
				| the pool size is still unstable.

		.new-swap__button
			button.button.primary
				| Stake

</template>
